### ISSUE TITLE
Check that student code finish at least last statement with ;

### ISSUE THREAD

**Issue by laendoor** [mumuki/mumuki-sqlite-runner#14]
For example, when exercise is `type: final_dataset`, the `final` query of teacher is concatenated with student solution. So, if exercise is DELETE sentence and student does not write `;`, the SQL final code is:

`DELETE from table where id = 1SELECT * from table;`

And the error is _Error: near line 1: near "select": syntax error_

But student doesn't write any _SELECT_ sentences; so error is confused.

![captura](https://user-images.githubusercontent.com/3334920/34362369-ab82ff48-ea51-11e7-84a0-5677d1b4b9a1.PNG)

Maybe we should try to check SQL sentences statically to report this types of errors without execute them in docker.

Suggestions?

**Comment by flbulgarelli** [comment]
Hi!

Yes, could. It is not a trivial task, but is feasible. 

However, for this specific task I would just check that the trimmed user code ends with a `;`.

**Comment by laendoor** [comment]
Do we check it in `validation_hook`?

**Comment by flbulgarelli** [comment]
No, since this will produce an `aborted` state. Validation hooks are suitable for performing security or well-formed request checks.

**Comment by flbulgarelli** [comment]
I recommend checking this in the normal test_hook.
