### ISSUE TITLE
Use mu-sql-table-rendered class

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-sqlite-runner#19]
@fedescarpa is working on the a new `mu-sql-table-rendered` class (see https://github.com/mumuki/mumuki-styles/pull/21#pullrequestreview-86934701). 

We should add the proper classes to the output tables when ready. 

We should also change the diff layout from left-to-right to up-to-bottom so big tables are displayed properly: 

![image](https://user-images.githubusercontent.com/677436/34623038-579d11f4-f22e-11e7-8182-8e6edc378f02.png)

**Comment by fedescarpa** [comment]
You need to generate this html

```html
<div class="mu-sql-table-rendered">
  <header>Personas</header>
  <table>
    <thead>
      <tr>
        <th class="mu-sql-table-pk">id_persona</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th class="mu-sql-table-fk">Pareja</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>Homero</td>
        <td>Simpson</td>
        <td>2</td>
      </tr>
      <tr>
        <td>2</td>
        <td>Marge</td>
        <td>Bouvier</td>
        <td>1</td>
      </tr>
      <tr>
        <td>3</td>
        <td>Moe</td>
        <td>Szyslak</td>
        <td>NULL</td>
      </tr>
    </tbody>
  </table>
</div>
```

to render this table

![image](https://user-images.githubusercontent.com/1039278/34625418-5a6bd56a-f237-11e7-8ebd-314465c8462b.png)

**Comment by laendoor** [comment]
I really like it!

I found this difficulties:

**Table name**

Not always results are over a single table. Also, sqlite worker returns plain dataset. If we want to display a table name or table view resulting of joins, we can ask teacher to wrote it in test YAML, but I don't know...

**Keys**

On the fly we don't know which fields are PK or FK. What I mean is that we can't deduce _keys_ from data returned from worker. We have to make an extra query based on schemas. Also, sometimes queries are over multiples tables, so we need to can deduce that tables and query _keys_ over all tables.

--

If you have a simple solutions for this problems, especially _Keys_, it would be great, because I love that keys in fields :smile: 

--

But we can implement mu-sql-table styles without this two problems anyway

**Comment by fedescarpa** [comment]
Hola!

Como default yo pondría siempre "Result" (pero intenacionalizado) y agregaría al YML una key más que sea `result_alias` en caso que el contenidista quiera que tenga un nombre específico la consulta resultante.

Respecto a las KEYs, si no se pueden obtener, no las pondría y ya.

Qué opinan @flbulgarelli, @leandrojdl?

**Comment by flbulgarelli** [comment]
De acuerdo!

**Comment by laendoor** [comment]
Me parece bien!

Una cosa más... Cómo seteamos los colores del diff? Hay algo predefinido o mantenemos los styles que ya existen?

**Comment by fedescarpa** [comment]
Buen punto... ahora me fijo de hacer el diff y mando screenshot a ver que les parece

**Comment by fedescarpa** [comment]
¿Algo como esto?

![image](https://user-images.githubusercontent.com/1039278/34726001-7c2c144c-f531-11e7-926c-da8a51aa0e73.png)

**Comment by fedescarpa** [comment]
igualmente, me puse a ver los ejemplos que hay, y no me termina de cerrar el diff.

Por ejemplo:
![image](https://user-images.githubusercontent.com/1039278/34726549-19ae916c-f533-11e7-9451-2cf249457c7c.png)

Acá la tabla no se ve bien alineada y creo que el diff, en esos casos meta mas ruido que solución.

En comparación con Gobstones o el runner de HTML, no se muestra un diff sino solo lo obtenido y lo que se esperaba, y creo que termina siendo mas claro mostrar menos.

Por otra parte, hay ejercicios donde el cambio difiere en decimales (numero entero o su flotante con cero como decimal) y el diff lo toma como distinto (ahora no encuentro ejercicio como para subir una imagen, pero si lo encuentro la subo)

Otra cosa es que en mumuki, el color verde, esta asociado a que algo está bien sin embargo, acá es que tenes una fila de más (o en un lugar que no es correcto) y creo que mete mas ruido.

En fin, esa es mi humilde opinión, no sé que pensarán ustedes. Me gustaría discutirlo

**Comment by flbulgarelli** [comment]
Yo también tengo mis dudas sobre la utilidad del diff, creo que hay casos (como por ejemplo, en los problemas de orden) en que confunde más  de lo que aclara. 

Estoy tentado a proponer sacarlo también. 

De todas formas, yo acá no innovaría en ese sentido. Iría por el estilo más simple posible y luego ataquemos el problema del diff sí/diff no, ¿les parece?

**Comment by fedescarpa** [comment]
Ok por mi

**Comment by laendoor** [comment]
Abrí un issue aparte para no mezclar la discusión del diff con el estilo de las tablas.

La seguimos en #20?
