### ISSUE TITLE
Support an always-passing exercise type

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-sqlite-runner#3]
We need it to implement hidden exercises. It should look like this: 

```yaml
type: display
query: select * from peliculas
```

@NadiaFinzi

**Comment by laendoor** [comment]
The point of this type is that student doesn't have to provide a solution?

**Comment by flbulgarelli** [comment]
Exactly. 

I want something similar to this: https://mumuki.io/exercises/259-fundamentos-primeros-programas-el-tablero

I want the user to be able to press continue, without entering any input, and see the result of a given query.

**Comment by flbulgarelli** [comment]
I actually just wrote the tests for that issue, but I haven't started yet with it. Do you have any suggestions on how to implement it? I understand I should write a new `parser`, right?

**Comment by laendoor** [comment]
Yes, a new `TestParser` is needed.

I think that copying `query` solution to `student` code (which is empty) the rest of code should work.

Maybe we need to change some code of `test_hook`. If you want I can do it and then finish with validation.

**Comment by flbulgarelli** [comment]
> Maybe we need to change some code of test_hook. If you want I can do it and then finish with validation.

That would be great! Thanks :smile:
