### ISSUE TITLE
Introduce a mu-sql-table class

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-sqlite-runner#4]
We a `mu-sql-table` style, that can be applied to tables, and should be added to `mumuki-styles`, that allows content editors to display an HTML table like an SQL table. 

@NadiaFinzi @fedescarpa

**Comment by flbulgarelli** [comment]
Some key ideas @NadiaFinzi showed me yesterday: 

* The tables should be able to distinguish primary key and foreign key columns, e.g. using a gold and silver key, like in the ERD
* The PK and FK should have a different font style - bold and italics. 
* It would be nice to highlight some rows using different colors - I propose using the standard mumuki's color palette. 

I also think it would be nice to display NULLs using a different style - but this is a nice to have.

**Comment by NadiaFinzi** [comment]
> -The PK and FK should have a different font style - bold and italics.

In fact, I used bold and italics because it was all I had, but I strongly prefer the highlight because I think that it's more impressive.

**Comment by flbulgarelli** [comment]
The format of the table spec should be simple to integrate with this runner's output.

**Comment by flbulgarelli** [comment]
@fedescarpa proposed those styles: 

![image](https://user-images.githubusercontent.com/677436/34611837-ebda70ec-f205-11e7-8ebd-574d29a19a23.png)


```
  <div
    class='mu-sql-table'
    data-name='Personas'
    data-columns='[{"name": "id_persona", "pk": true}, "Nombre", "Apellido", {"name": "Pareja", "fk": true}]'
    data-rows='[
      [1, "Homero", "Simpson", 2],
      [2, "Marge", "Bouvier", 1],
      [3, "Moe", "Szyslak", null]
    ]'>
  </div>
```

**Comment by flbulgarelli** [comment]
I like them, but I am afraid they may be difficult to generate from the runner. What do you @leandrojdl ?
