### ISSUE TITLE
Define styles for displaying entity-relationship diagrams

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-sqlite-runner#5]
We need to be able to show SQL tables using simple html/css components defined in mumuki-styles.

It should be consistent with `mu-browser` and `mu-file-browser`. 

@NadiaFinzi @fedescarpa

**Comment by fedescarpa** [comment]
This gonna take a while.

**Comment by flbulgarelli** [comment]
Done. 

* See docs: https://github.com/mumuki/mumuki-styles/blob/master/README.md#mu-erd
* See sample and PR: https://github.com/mumuki/mumuki-styles/pull/15
