### ISSUE TITLE
Improve error reporting of test syntax errors

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-sqlite-runner#8]
When editing an exercise from the bibliotheca, if your test is on some way wrong, you will get awful stacktraces, like 

```
/usr/local/bundle/gems/mumuki-sqlite-runner-3.1.0/lib/test_hook.rb:140:in `block in parse_tests'
/usr/local/bundle/gems/mumuki-sqlite-runner-3.1.0/lib/test_hook.rb:138:in `map'
/usr/local/bundle/gems/mumuki-sqlite-runner-3.1.0/lib/test_hook.rb:138:in `parse_tests'
/usr/local/bundle/gems/mumuki-sqlite-runner-3.1.0/lib/test_hook.rb:45:in `compile_file_content'
/usr/local/bundle/gems/mumukit-2.18.1/lib/mumukit/templates/file_hook.rb:10:in `compile'
/usr/local/bundle/gems/mumukit-2.18.1/lib/mumukit/server/test_server.rb:87:in `compile_and_run'
/usr/local/bundle/gems/mumukit-2.18.1/lib/mumukit/server/test_server.rb:63:in `run_tests!'
/var/www/runner/lib/prefer_static_analysis.rb:7:in `evaluate!'
/usr/local/bundle/gems/mumukit-
```

Such traces don't help content writer to find where is the issue. We should add some validations:

  1. Validate that YAML is well formed
  2. Validate that the test type is right
  3. Validate that all the required fields are present, and that there are no spurious fields

And generate proper error messages, too

**Comment by laendoor** [comment]
What do you mean with "no spurious fields"?

Do you want that each `type` should have only defined types and no others? For example, in `type: datasets`:

```YAML
type: datasets
expected: |
  id|name
  1|foo
```

Is valid but

```YAML
type: datasets
expected: |
  id|name
  1|foo
bar: baz
```

is not valid?

**Comment by flbulgarelli** [comment]
> What do you mean with "no spurious fields"?
> Do you want that each type should have only defined types and no others? 

Exactly. I don't want the user to introduce extra fields by accident. He could believe they mean something, but they don't

**Comment by laendoor** [comment]
OK, no problem
